### ISSUE TITLE
这个插件的意义是？

### ISSUE THREAD

**Issue by g-plane** [aladdin-add/eslint-plugin-no-autofix#1]
为什么把 ESLint 内置的 autofix 也要关闭？

**Comment by aladdin-add** [comment]
可以让用户关闭某些内置规则的autofix. 现在想到的一个场景是 editor: autofix-on-save:

![eslint-no-autofix](https://user-images.githubusercontent.com/13050025/52712807-a9347080-2fd0-11e9-9004-ac9db748cfde.gif)

**Comment by aladdin-add** [comment]
https://github.com/Microsoft/vscode-eslint/issues/208
